apiVersion: skaffold/v4beta10
kind: Config
metadata:
    name: mailing
build:
  artifacts:
    - image: mailing
      docker:
        dockerfile: ./Dockerfile
deploy:
  helm:
    releases:
      - name: mailing
        chartPath: helm
        setValueTemplates:
          config.db.username: postgres
          config.db.password: postgres
          config.db.name: postgres
          config.db.host: mailing-postgresql
          config.db.port: 5432

          global.postgresql.auth.password: postgres
          global.postgresql.auth.username: postgres
          global.postgresql.auth.database: postgres
portForward:
  - resourceType: service
    resourceName: mailing
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: mailing-postgresql
    port: 5432
    localPort: 5432
