apiVersion: v1
kind: ConfigMap
metadata:
  name: mailing-config
data:
  MAILING_DB_NAME: {{ .Values.config.db.name }}
  MAILING_DB_PORT: {{ .Values.config.db.port | quote}}
  MAILING_DB_HOST: {{ .Values.config.db.host }}